### ISSUE TITLE
PHP_ICO

### ISSUE THREAD

**Issue by MDReal32** [chrisbliss18/php-ico#11] opened 2018-09-05 09:56 UTC
This is not works. I send png files how says but it return to me png file. What to Hell?

**Comment by chrisbliss18** [comment] 2018-09-06 22:21
I can't help you unless you provide more details. Can you give me the code you ran and the source PNG file you used?

**Comment by chrisbliss18** [comment] 2018-09-14 18:52
Closing since I doubt I'll get a reply, and I think the issue is user error rather than a problem with the project.

**Closed as completed by chrisbliss18** 2018-09-14 18:52 UTC
